### ISSUE TITLE
resetting with "out" instead of "rst"?

### ISSUE THREAD

**Issue by tmasquelier** [fzenke/spytorch#2]
* This is a comment, not an issue *

Hi Friedemann,
First of thanks a lot for these great tutorials, I've enjoyed a lot playing with them, and I've learned a lot :-)
One question: in the run_snn function, why do you bother constructing the "rst" tensor? Why don't you subtract the "out" tensor, which also contains the output spikes? I've tried, and it seems to work.
Just curious.
Best,

Tim

**Comment by fzenke** [comment]
Thanks. I am glad you found it helpful.

The rst tensor is introduced to prevent gradients from flowing through the reset. You can achieve the same by detaching the out tensor. Why is this done? Empirically, I found that back-propagating through the reset term leads to problems, especially when the surrogate derivative is not standardized (it is standardized in the Tutorial however). The best explanation I can offer at the moment is the following. Suppose you use the derivative of a sigmoid with a slope of 100 at the origin as your surrogate. This surrogate derivative also contains the prefactor 100 (in the tutorial it is dropped, which is probably why you get decent performance irrespectively). Since the reset term enters with a negative sign, the local gradient begins to "feel" the reset of the spike before it actually happens. This renders the threshold repelling which ultimately impedes the creation of hidden layer spikes where you might actually want them. This is the motivation behind the rst tensor. I hope this makes sense.

Having said all this, I think there remains some interesting analytical work to be done to understand the cost benefit trade-off between standardizing the surrogate derivative and dropping it from the gradient entirely.

**Comment by tmasquelier** [comment]
Thanks for the explanation.
One option could be not resetting at all, and using an adaptive threshold as in:
https://www.frontiersin.org/articles/10.3389/neuro.10.009.2009/full
Do you think that would work?
The threshold discontinuity may cause problems though.

**Comment by fzenke** [comment]
If the adaptive threshold is formally equivalent to a reset, then I expect it to suffer from the same problems. I wonder how Ben Huh & Terry get around this in their framework. It seems they would have to deal with a real (partial) reset before the spike has occurred which may prevent the spike from from occurring in the first place.

**Comment by fzenke** [comment]
It just came to my mind that Guillaume Bellec et al. also use a moving threshold to bridge long timescales.

**Comment by fzenke** [comment]
However, as I said. In my hands, the reset has always proven problematic. Here is a snipped from a recent poster (https://fzenke.net/wp-content/uploads/2019/02/2019cosyne-zenke_vogels.pdf).

![image](https://user-images.githubusercontent.com/5672284/55179400-35fd4d00-517f-11e9-8b83-e967bb4ef787.png)

**Comment by tmasquelier** [comment]
Thanks!

**Comment by yizx6** [comment]
> Thanks. I am glad you found it helpful.
> 
> The rst tensor is introduced to prevent gradients from flowing through the reset. You can achieve the same by detaching the out tensor. Why is this done? Empirically, I found that back-propagating through the reset term leads to problems, especially when the surrogate derivative is not standardized (it is standardized in the Tutorial however). The best explanation I can offer at the moment is the following. Suppose you use the derivative of a sigmoid with a slope of 100 at the origin as your surrogate. This surrogate derivative also contains the prefactor 100 (in the tutorial it is dropped, which is probably why you get decent performance irrespectively). Since the reset term enters with a negative sign, the local gradient begins to "feel" the reset of the spike before it actually happens. This renders the threshold repelling which ultimately impedes the creation of hidden layer spikes where you might actually want them. This is the motivation behind the rst tensor. I hope this makes sense.
> 
> Having said all this, I think there remains some interesting analytical work to be done to understand the cost benefit trade-off between standardizing the surrogate derivative and dropping it from the gradient entirely.

Hi, Zenke, sorry for bringing this up again. I wonder why the gradient can feel the reset of the output spikes. The effect of the reset term is not trainable, so  I think there seems to be no difference between the two cases.

**Comment by fzenke** [comment]
It is about whether surrogate gradients can flow through the reset or not. I wrote a paper about it. Check out https://doi.org/10.1162/neco_a_01367 Figure 5. I hope that clarifies it further.
